apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: PROJECT-BACK/IMAGE
    newName: fil7er/nodejs-crud
  - name: PROJECT-DB/IMAGE
    newName: mongo
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/statefullset_db.yaml
  - manifests/service_db.yaml
  - manifests/ingress.yaml