apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: some-crud
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 10m
    successCondition: result > 750
    provider:
      prometheus:
        address: 
          valueFrom:
              secretKeyRef:
                key: prometheus_url
                name: nodejs-crud-secret
        query: |
          scalar(
            sum(
              container_cpu_usage_seconds_total{namespace="default"}))