apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-crud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-crud
  template:
    metadata:
      labels:
        app: nodejs-crud
    spec:
      containers:
        - name: nodejs-crud
          image: PROJECT-BACK/IMAGE
          ports:
            - containerPort: 3013
          env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: nodejs-crud-db-secret
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: nodejs-crud-db-secret
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: nodejs-crud-db-secret
          - name: NATS_URL
            value: nats://my-nats:4222
          resources:
            limits:
              memory: 120Mi
              cpu: 250m
          readinessProbe:
            exec:
              command:
                - nc
                - -vz
                - nodejs-crud-db-svc
                - "27017"
            failureThreshold: 4
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3013
            initialDelaySeconds: 40
            periodSeconds: 20