apiVersion: v1
kind: Secret
metadata:
  name: nodejs-crud-db-secret
  namespace: my-namespace
type: Opaque
data:
  user: c29tZQ==
  password: U29tZXBhc3M=
stringData:
  user: some
  password: Somepass
