apiVersion: v1
kind: Service
metadata:
  name: nodejs-crud-db-svc
  namespace: some-crud
spec:
  type: NodePort
  selector:
    app: nodejs-crud-db
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30081
