apiVersion: v1
kind: Service
metadata:
  name: nodejs-crud-svc
  namespace: some-crud
spec:
  type: LoadBalancer
  selector:
    app: nodejs-crud # This is the app as declared in the deployment.
  ports:
    - name: http
      protocol: TCP
      port: 3013 # This is a port that is available to the cluster, in this case it can be ~ anything
      targetPort: 3013 # This is the target port