apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullset-db
spec:
  selector:
    matchLabels:
      app: nodejs-crud-db
  serviceName: nodejs-crud-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-crud-db
    spec:
      containers:
      - name: mongodb
        image: PROJECT-DB/IMAGE
        ports:
        - containerPort: 27017
          name: mongodb
        env:
          - name: MONGODB_ROOT_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: nodejs-crud-db-secret
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: nodejs-crud-db-secret
