apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullset-db
  namespace: some-crud
spec:
  selector:
    matchLabels:
      app: nodejs-crud-db
  serviceName: nodejs-crud-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-crud-db
    spec:
      containers:
      - name: mongodb
        image: PROJECT-DB/IMAGE
        ports:
        - containerPort: 27017
          name: mongodb
        env:
          - name: MONGODB_ROOT_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: nodejs-crud-db-secret
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: nodejs-crud-db-secret
        livenessProbe:
          exec:
            command:
                - bash
                - "-c"
                - |
                  mongo -u $MONGODB_ROOT_USER -p $MONGODB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - bash
              - "-c"
              - |
                mongo -u $MONGODB_ROOT_USER -p $MONGODB_ROOT_PASSWORD --eval db.adminCommand\(\"ping\"\)
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
